package RoomReservationApp;


/**
* RoomReservationApp/CampusOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from drrs.idl
* Wednesday, November 1, 2017 4:35:14 o'clock PM EDT
*/

public interface CampusOperations 
{

  // admin interface
  boolean lookupAdmin (String id);
  String generateAdminId ();
  boolean createRoom (String date, int roomNo, RoomReservationApp.TimeSlot[] timeSlots);
  boolean deleteRoom (String date, int roomNo, RoomReservationApp.TimeSlot[] timeSlots);
  boolean resetBookings ();

  // student interface
  boolean lookupStudent (String id);
  String generateStudentId ();
  boolean getAvailableTimeSlots (String date, RoomReservationApp.AvailTimeSlotsHolder availTimeSlots);
  String bookRoom (String studentId, String code, String date, int roomNumber, RoomReservationApp.TimeSlot timeSlot);
  boolean cancelBooking (String studentId, String bookingId);
  String changeBooking (String bookingId, String code, String date, int roomNumber, RoomReservationApp.TimeSlot timeSlot);
} // interface CampusOperations
