package RoomReservationApp;


/**
* RoomReservationApp/TimeSlotsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from drrs.idl
* Wednesday, November 1, 2017 4:35:14 o'clock PM EDT
*/

public final class TimeSlotsHolder implements org.omg.CORBA.portable.Streamable
{
  public RoomReservationApp.TimeSlot value[] = null;

  public TimeSlotsHolder ()
  {
  }

  public TimeSlotsHolder (RoomReservationApp.TimeSlot[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RoomReservationApp.TimeSlotsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RoomReservationApp.TimeSlotsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RoomReservationApp.TimeSlotsHelper.type ();
  }

}
